```{r}
library(httr2)
library(tidyverse)
library(rvest)
library(tibble)
library(readr)
library(string)
```

**WEB SCRAPING - 121 Franchises**

```{r}
#Web Scrape - Franchise - GOOD

#Get the website to scrape franchise title
title <- read_html("https://en.wikipedia.org/wiki/List_of_highest-grossing_media_franchises")|>
  
#Get the data from website - (1st column - Franchise)
html_nodes("td:nth-child(1)")|>
  
#Print data out neatly and save to value
html_text2() -> franchise_title

#Clean the data - Convert "Franchise" column to a dataframe
title <- data.frame(title)

##Remove unwanted empty rows
title <- title |>
filter(title != "") 

##Remove unwanted rows at the end of the "Franchise" column
title <- title[-122, ]
title <-tibble(title)
```

```{r}
#Web Scrape - Year of Inception - GOOD

#Get the website to scrape year
year <- read_html("https://en.wikipedia.org/wiki/List_of_highest-grossing_media_franchises")|> 

#Get the data from website - (2nd column - Year of Inception)
html_nodes("td:nth-child(2)")|>

#Print data out neatly and save to value
html_text2() -> year_of_inception

#Clean the data - Convert "Year of Inception" column to a dataframe
year_of_inception_df <- data.frame(year_of_inception)

##Remove unwanted rows in the "Year of Inception" column
year_of_inception_df <- year_of_inception_df[1:121,]
year_1 <-tibble(year_of_inception_df)

##Remove unwanted characters at the end of the values in the column
year_1|>
  mutate(year = parse_number(year_of_inception_df))|>
  select(year) -> release_year
```

```{r}
#Web Scrape - Total Revenue - GOOD

#Get the website to scrape total revenue
read_html("https://en.wikipedia.org/wiki/List_of_highest-grossing_media_franchises")|>

#Get the data from website - (3rd column - Total Revenue) 
html_elements("td:nth-child(3)")|>

#print out the data neatly
html_text2() -> total_revenue

#Clean the data - Convert "Total Revenue" column to a dataframe
total_revenue_df <- data.frame(total_revenue)

##Remove unwanted parts of the "Total Revenue" column - remove the "\$" sign and "Billion" string - Total Revenue will be expressed as a number in Billions
total_revenue_df|>
  mutate(revenue = parse_number(total_revenue))|>
  select(revenue) -> movie_revenue
```

```{r}
#Web Scraping - Original Medium - GOOD
read_html("https://en.wikipedia.org/wiki/List_of_highest-grossing_media_franchises")|>

#Get the data from website - (5th column - Original Medium)
html_elements("td:nth-child(5)")|>
  
#Print out data neatly and save to value
html_text2() -> original_medium

#Clean the data - Convert "Original Medium" column to a dataframe
original_medium_df <- data.frame(original_medium)

#Create a tibble of all 4 columns
tibble(title,release_year, original_medium_df, movie_revenue) -> movies

```
